// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHn7Ziup8Nui9jk3kcmB4fbzUWvxKTh8U',
    appId: '1:340082344368:web:1b842c62cfca9120659675',
    messagingSenderId: '340082344368',
    projectId: 'isthmary',
    authDomain: 'isthmary.firebaseapp.com',
    storageBucket: 'isthmary.firebasestorage.app',
    measurementId: 'G-KGX2KLWYD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbCXcUbdklKj_oJzEmyFEg1WsIf0pg6yo',
    appId: '1:340082344368:android:a3f66a2a8da78b54659675',
    messagingSenderId: '340082344368',
    projectId: 'isthmary',
    storageBucket: 'isthmary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk7QUcN-7nCM8EdzUQMV4_QG7bTNHF0NU',
    appId: '1:340082344368:ios:3cd1be36d2d93d2e659675',
    messagingSenderId: '340082344368',
    projectId: 'isthmary',
    storageBucket: 'isthmary.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk7QUcN-7nCM8EdzUQMV4_QG7bTNHF0NU',
    appId: '1:340082344368:ios:3cd1be36d2d93d2e659675',
    messagingSenderId: '340082344368',
    projectId: 'isthmary',
    storageBucket: 'isthmary.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHn7Ziup8Nui9jk3kcmB4fbzUWvxKTh8U',
    appId: '1:340082344368:web:4fb9e778038520da659675',
    messagingSenderId: '340082344368',
    projectId: 'isthmary',
    authDomain: 'isthmary.firebaseapp.com',
    storageBucket: 'isthmary.firebasestorage.app',
    measurementId: 'G-SWBVDSK67M',
  );
}
